### PR TITLE
Edit modman to use only necessary files

### PR DESCRIPTION
**Pull request by giuseppemorelli**
Hello Peter,
changes with this pull requrest:
- modman: use (or copy) only necessary files into magento folder

Hope this helps

### CODE REVIEW

**Comment by peterjaap** [comment]
Hi @giuseppemorelli,

I've merged your PR but I'm not sure why you want to do this; yes, a Magerun extension cán be added to the project, but it really shouldn't. Addons should be added in the global scope on your machine.

**Comment by giuseppemorelli** [comment]
Hi @peterjaap, I don't use addons globally because in one single machine I have more project and in each project I create or edit (sometime) the single addons (based on the project).
In some cases some project doesn't have the permission to view some additional command (based on the contract with the customer).

Do you have any advice to manage this situation?

**Comment by peterjaap** [comment]
I don't understand, do you use these commands on a production server?

**Comment by giuseppemorelli** [comment]
In staging environment, but sometimes is shared with the customer IT. So I need some "level" of permission.

**Pull request merged**
