### PR TITLE
Updating template var check with vars from 1.9.2.2 install script

### PR DESCRIPTION
**Pull request by steverobbins**
3 additional vars were added in the official patch

* `trans_email/ident_general/email`
* `trans_email/ident_support/email`
* `trans_email/ident_support/name`

### CODE REVIEW

**Comment by tkn98** [comment]
+1 - thanks for quick PR, @peterjaap please pull this in (-:

**Comment by rob3000** [comment]
+1

**Comment by cmuench** [comment]
+1

**Comment by cmuench** [comment]
Thanks

**Comment by tkn98** [comment]
Thx for the update, just gave current master a try. Works like a charm!

**Pull request merged**
