### PR TITLE
Refactored Media commands

### PR DESCRIPTION
**Pull request by JeroenBoersma**
+ dropped the need for external commands like fdupes
+ speed optimized all commands(especially db lookups, they where so slooowww)
+ read all files and hashes, show progress along
+ re-used code whenever i can for several commands
+ added support for options like -d for dryrun without asking

### CODE REVIEW

**Comment by hostep** [comment]
@JeroenBoersma: nice job!
Although haven't actually checked out your code changes, but my eye spotted that you ignored the `placeholder` directory. You should actually also ignore the `watermark` directory. See this similar Magento module: https://github.com/sreichel/magento-Defcon2-Imaclean/blob/8c3245bb96a12c619ba035c242b3300b656c9d6f/app/code/community/Defcon2/Imaclean/Helper/Data.php#L23

**Comment by JeroenBoersma** [comment]
@hostep thanks for pointing it out! Fixed in the last commits, also it would match files too, worked this out too

**Comment by gwillem** [comment]
Awesome! One noob question: dropping the reference from the database does not remove possible external references (inbound http links). Would that be a problem or does nobody in their right mind link to media stuff directly? 

Are there any other possible side effects from using the media cleanup functions? Ie, should we recommend our customers to run this unconditionally?

**Comment by JeroenBoersma** [comment]
I would recommend that people link to products and not individual images, than this should not give problems at all, one should clean FPC afterwards(if any)
Of coarse people should be aware of the deadlinks problem if linked externally.

I've dropped several Gigabytes on different shops, one could do a dry-run to see which effect it would have on their shops.

**Comment by peterjaap** [comment]
Awesome @JeroenBoersma !! :)

**Pull request merged**
